#!/bin/bash
count=$(yay -Pu | wc -l)
if [ $count == 0 ]
then 
    text=Updates
    count=Keine
elif [ $count == 1 ]
then
    text=Update
else
    text=Updates
fi
notify-send -t 5000 "$count $text" "$(yay -Pu | sed -r "s/([a-z_A-Z0-9\-]*) .*/\1/" | paste -sd "," | sed -r "s/,/, /g")"

