#!/bin/bash
if which yay &> /dev/null; then
    cmd="yay -Pu"
elif which yaourt &> /dev/null; then
    cmd="yaourt -Qu"
elif which checkupdates &> /dev/null; then
    cmd="checkupdates"
else
    cmd="pacman -Qu"
fi
if [ $1 == "-s" ]
then
    sleep $2
fi
count=$($cmd | wc -l)
if [ $count == 0 ]
then
    text=Updates
    count=Keine
elif [ $count == 1 ]
then
    text=Update
else
    text=Updates
fi
notify-send "$count $text" "$($cmd | sed -r -e "s/([a-z_A-Z0-9\-]*) .*/\1/" | paste -sd "," | sed -r -e "s/,/, /g" -e "s/\x1B\[(([0-9]{1,2})?(;)?([0-9]{1,2})?)?[m,K,H,f,J]//g")"
