version: '2' 

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    restart: always
    ports:
      - 25565:25565
    volumes:
      - /home/florian/minecraft/server_1:/data
    environment:
      - EULA=TRUE 
      - ENABLE_AUTOPAUSE=TRUE 
      - AUTOPAUSE_TIMEOUT_EST=900 
      - MAX_MEMORY=5G
