version: '3.4'

services:
  impostor:
    image: aeonlucid/impostor:nightly
    container_name: impostor
    ports:
      - 22023:22023/udp
    volumes:
      - /home/florian/settings/docker/impostor/config.json:/app/config.json # For easy editing of the config
    #  - /path/to/local/plugins:/app/plugins         # Only needed if using plugins
    #  - /path/to/local/libraries:/app/libraries     # Only needed if using external libraries
